# Generated by Django 2.2.3 on 2019-07-25 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190725_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional, upload an image to assign it to the product category', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(help_text='Assign this product to a user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='check if you want to add the product to the featured list'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, help_text='check if you want to assign this product for free shipping'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, help_text='This is optional for more images of the product', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='This is optional for more images of the product', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='This is optional for more images of the product', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, help_text='This is optional for more images of the product', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, default=None, help_text='if there is no image to uplad you can add a link here', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=5, help_text='By default this will be set to 5'),
        ),
    ]
