# Generated by Django 2.2.3 on 2019-07-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190725_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank if there is no discount', null=True),
        ),
    ]
