# Generated by Django 2.2.3 on 2019-07-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190725_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_until',
            field=models.DateField(blank=True, help_text='Leave blank if there is no discount', null=True),
        ),
    ]
